# Generated by Django 5.0.4 on 2026-05-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
